output_root: "outputs"
output_version: "baseline"
backup_name: "weights"
log_name: "logs"

labels: ["trepang"]

data_root_dir: "./data/VOCdevkit/onedet_cache"

train:
    dataset: "train"
    stdout: True
    gpus: "0"
    nworkers: 16
    pin_mem: True

    momentum: 0.9
    decay: 0.0005

    clear: False

    warmup_lr: 0.0001
    lr_steps: [400,700,900,1000, 20000] 
    lr_rates: [0.0001,0.0005,0.0005,0.0001, 0.00001] 
    max_batches: 16000
    resize_interval: 10

    backup_interval: 200
    backup_steps: [1000, 60000]
    backup_rates: [10000, 200]

    input_shape: [608, 608]
    batch_size: 64
    mini_batch_size: 16
    weights: "./outputs/Yolov2/baseline/weights/backup.pt"

test:
    dataset: "test"
    stdout: True
    gpus: "0"
    nworkers: 16
    pin_mem: True

    input_shape: [608, 608]
    batch_size: 1
    weights: "./outputs/Yolov2/baseline/weights/12000_final.dw"

    conf_thresh: 0.005
    nms_thresh: 0.45

    results: "results"

speed:
    gpus: "0"
    batch_size: 1
    max_iters: 200
    input_shape: [576, 576]
