# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets, QtNetwork
from PyQt5.QtGui import *
import datetime
from PyQt5.QtCore import pyqtSlot,pyqtSignal,QByteArray,QDataStream
import sys

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(916, 509)
        self.formGroupBox2 = QtWidgets.QGroupBox(Form)
        self.formGroupBox2.setGeometry(QtCore.QRect(250, 10, 167, 301))
        self.formGroupBox2.setObjectName("formGroupBox2")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox2)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox2)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox2)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox2)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox2)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox2)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox2)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox2)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox2)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox2)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.close_button)
        self.verticalGroupBox1 = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox1.setGeometry(QtCore.QRect(10, 310, 321, 81))
        self.verticalGroupBox1.setObjectName("verticalGroupBox1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox1)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox1)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.verticalLayout.addWidget(self.s2__receive_text)
        self.verticalGroupBox2 = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox2.setGeometry(QtCore.QRect(10, 390, 321, 101))
        self.verticalGroupBox2.setObjectName("verticalGroupBox2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox2)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox2)
        self.s3__send_text.setObjectName("s3__send_text")
        self.verticalLayout_2.addWidget(self.s3__send_text)
        self.s3__send_button = QtWidgets.QPushButton(Form)
        self.s3__send_button.setGeometry(QtCore.QRect(350, 410, 61, 31))
        self.s3__send_button.setObjectName("s3__send_button")
        self.s3__clear_button = QtWidgets.QPushButton(Form)
        self.s3__clear_button.setGeometry(QtCore.QRect(350, 450, 61, 31))
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setGeometry(QtCore.QRect(430, 380, 161, 101))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.s2__clear_button = QtWidgets.QPushButton(Form)
        self.s2__clear_button.setGeometry(QtCore.QRect(350, 340, 61, 31))
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.formGroupBox4 = QtWidgets.QGroupBox(Form)
        self.formGroupBox4.setGeometry(QtCore.QRect(10, 10, 231, 301))
        self.formGroupBox4.setObjectName("formGroupBox4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formGroupBox4)
        self.formLayout_3.setContentsMargins(10, 10, 10, 10)
        self.formLayout_3.setSpacing(10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.s1__lb_7 = QtWidgets.QLabel(self.formGroupBox4)
        self.s1__lb_7.setObjectName("s1__lb_7")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_7)
        self.s1__box_9 = QtWidgets.QComboBox(self.formGroupBox4)
        self.s1__box_9.setObjectName("s1__box_9")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.s1__box_9.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_9)
        self.s1__lb_8 = QtWidgets.QLabel(self.formGroupBox4)
        self.s1__lb_8.setObjectName("s1__lb_8")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_8)
        self.s1__box_8 = QtWidgets.QComboBox(self.formGroupBox4)
        self.s1__box_8.setObjectName("s1__box_8")
        self.s1__box_8.addItem("")
        self.s1__box_8.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_8)
        self.s1__lb_9 = QtWidgets.QLabel(self.formGroupBox4)
        self.s1__lb_9.setObjectName("s1__lb_9")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.s1__lb_9)
        self.state_label_2 = QtWidgets.QLabel(self.formGroupBox4)
        self.state_label_2.setText("")
        self.state_label_2.setTextFormat(QtCore.Qt.AutoText)
        self.state_label_2.setScaledContents(True)
        self.state_label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label_2.setObjectName("state_label_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.state_label_2)
        self.s1__lb_11 = QtWidgets.QLabel(self.formGroupBox4)
        self.s1__lb_11.setObjectName("s1__lb_11")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_11)
        self.s1__box_10 = QtWidgets.QComboBox(self.formGroupBox4)
        self.s1__box_10.setObjectName("s1__box_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_10)
        self.s1__lb_10 = QtWidgets.QLabel(self.formGroupBox4)
        self.s1__lb_10.setObjectName("s1__lb_10")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_10)
        self.s1__box_11 = QtWidgets.QComboBox(self.formGroupBox4)
        self.s1__box_11.setObjectName("s1__box_11")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_11)
        self.close_button_2 = QtWidgets.QPushButton(self.formGroupBox4)
        self.close_button_2.setObjectName("close_button_2")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.close_button_2)
        self.open_button_2 = QtWidgets.QPushButton(self.formGroupBox4)
        self.open_button_2.setObjectName("open_button_2")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.open_button_2)
        self.whatchImagrbutton = QtWidgets.QPushButton(self.formGroupBox4)
        self.whatchImagrbutton.setObjectName("whatchImagrbutton")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.whatchImagrbutton)
        self.whatchVideogrbutton = QtWidgets.QPushButton(self.formGroupBox4)
        self.whatchVideogrbutton.setObjectName("whatchVideogrbutton")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.whatchVideogrbutton)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(430, 30, 471, 341))
        self.label_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.formGroupBox5 = QtWidgets.QGroupBox(Form)
        self.formGroupBox5.setGeometry(QtCore.QRect(600, 380, 171, 71))
        self.formGroupBox5.setObjectName("formGroupBox5")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formGroupBox5)
        self.formLayout_4.setContentsMargins(10, 10, 10, 10)
        self.formLayout_4.setSpacing(10)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formGroupBox5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_4)
        self.formGroupBox3 = QtWidgets.QGroupBox(Form)
        self.formGroupBox3.setGeometry(QtCore.QRect(780, 380, 121, 101))
        self.formGroupBox3.setObjectName("formGroupBox3")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formGroupBox3)
        self.formLayout_5.setContentsMargins(10, 10, 10, 10)
        self.formLayout_5.setSpacing(10)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_6 = QtWidgets.QLabel(self.formGroupBox3)
        self.label_6.setObjectName("label_6")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_3)
        self.startTcpconnect = QtWidgets.QPushButton(Form)
        self.startTcpconnect.setGeometry(QtCore.QRect(600, 460, 80, 23))
        self.startTcpconnect.setObjectName("startTcpconnect")
        self.stopTcpconnect = QtWidgets.QPushButton(Form)
        self.stopTcpconnect.setGeometry(QtCore.QRect(690, 460, 80, 23))
        self.stopTcpconnect.setObjectName("stopTcpconnect")
        self.verticalGroupBox1.raise_()
        self.verticalGroupBox2.raise_()
        self.formGroupBox2.raise_()
        self.s3__send_button.raise_()
        self.s3__clear_button.raise_()
        self.formGroupBox1.raise_()
        self.s2__clear_button.raise_()
        self.formGroupBox4.raise_()
        self.label_3.raise_()
        self.formGroupBox5.raise_()
        self.formGroupBox3.raise_()
        self.startTcpconnect.raise_()
        self.stopTcpconnect.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.formGroupBox2.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "2400"))
        self.s1__box_3.setItemText(2, _translate("Form", "4800"))
        self.s1__box_3.setItemText(3, _translate("Form", "9600"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.verticalGroupBox1.setTitle(_translate("Form", "接受区"))
        self.verticalGroupBox2.setTitle(_translate("Form", "发送区"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RecordRouterData</p></body></html>"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.s3__clear_button.setText(_translate("Form", "清除"))
        self.formGroupBox1.setTitle(_translate("Form", "串口状态"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.formGroupBox4.setTitle(_translate("Form", "海参检测设置"))
        self.s1__lb_7.setText(_translate("Form", "检测方式:"))
        self.s1__box_9.setItemText(0, _translate("Form", "实时检测"))
        self.s1__box_9.setItemText(1, _translate("Form", "检测本地图像"))
        self.s1__box_9.setItemText(2, _translate("Form", "检测本地视频"))
        self.s1__box_9.setItemText(3, _translate("Form", "画面传输不检测"))
        self.s1__lb_8.setText(_translate("Form", "机器人控制方式"))
        self.s1__box_8.setItemText(0, _translate("Form", "远程遥控"))
        self.s1__box_8.setItemText(1, _translate("Form", "按键控制"))
        self.s1__lb_9.setText(_translate("Form", "设置提示:"))
        self.s1__lb_11.setText(_translate("Form", "本地图像:"))
        self.s1__lb_10.setText(_translate("Form", "本地视频:"))
        self.close_button_2.setText(_translate("Form", "检测"))
        self.open_button_2.setText(_translate("Form", "检测"))
        self.whatchImagrbutton.setText(_translate("Form", "预览"))
        self.whatchVideogrbutton.setText(_translate("Form", "预览"))
        self.formGroupBox5.setTitle(_translate("Form", "网络连接状态"))
        self.formGroupBox3.setTitle(_translate("Form", "检测结果"))
        self.label_6.setText(_translate("Form", "海参数量:"))
        self.lineEdit_3.setText(_translate("Form", "0"))
        self.startTcpconnect.setText(_translate("Form", "开始接收"))
        self.stopTcpconnect.setText(_translate("Form", "停止接收"))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setMaximumSize(800, 650)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.CameraDisplayLable = QtWidgets.QLabel(self.centralWidget)
        self.CameraDisplayLable.setGeometry(QtCore.QRect(10, 10, 778, 586))
        self.CameraDisplayLable.setMinimumSize(QtCore.QSize(0, 0))
        self.CameraDisplayLable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CameraDisplayLable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CameraDisplayLable.setText("")
        self.CameraDisplayLable.setObjectName("CameraDisplayLable")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 721, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuDete = QtWidgets.QMenu(self.menuBar)
        self.menuDete.setObjectName("menuDete")
        self.menuRoter = QtWidgets.QMenu(self.menuBar)
        self.menuRoter.setObjectName("menuRoter")
        self.menuClearData = QtWidgets.QMenu(self.menuBar)
        self.menuClearData.setObjectName("menuClearData")
        self.menuImage = QtWidgets.QMenu(self.menuBar)
        self.menuImage.setObjectName("menuImage")
        self.menuROV = QtWidgets.QMenu(self.menuBar)
        self.menuROV.setObjectName("menuROV")
        MainWindow.setMenuBar(self.menuBar)
        self.actionoDetBenShipin = QtWidgets.QAction(MainWindow)
        self.actionoDetBenShipin.setObjectName("actionoDetBenShipin")
        self.actionClearRoter = QtWidgets.QAction(MainWindow)
        self.actionClearRoter.setObjectName("actionClearRoter")
        self.actionCutoutImage = QtWidgets.QAction(MainWindow)
        self.actionCutoutImage.setObjectName("actionCutoutImage")
        self.actionDetBenImage = QtWidgets.QAction(MainWindow)
        self.actionDetBenImage.setObjectName("actionDetBenImage")
        self.actionScanRoter = QtWidgets.QAction(MainWindow)
        self.actionScanRoter.setObjectName("actionScanRoter")
        self.actionDetTimer = QtWidgets.QAction(MainWindow)
        self.actionDetTimer.setObjectName("actionDetTimer")
        self.actionConnRoter = QtWidgets.QAction(MainWindow)
        self.actionConnRoter.setObjectName("actionConnRoter")
        self.actionCheckIp = QtWidgets.QAction(MainWindow)
        self.actionCheckIp.setObjectName("actionCheckIp")
        self.actionKeyControl = QtWidgets.QAction(MainWindow)
        self.actionKeyControl.setObjectName("actionKeyControl")
        self.actionRoterControl = QtWidgets.QAction(MainWindow)
        self.actionRoterControl.setObjectName("actionRoterControl")
        self.actionOpenRoter = QtWidgets.QAction(MainWindow)
        self.actionOpenRoter.setObjectName("actionOpenRoter")
        self.menuDete.addAction(self.actionDetBenImage)
        self.menuDete.addAction(self.actionoDetBenShipin)
        self.menuDete.addAction(self.actionDetTimer)
        self.menuRoter.addAction(self.actionScanRoter)
        self.menuRoter.addAction(self.actionConnRoter)
        self.menuRoter.addAction(self.actionOpenRoter)
        self.menuClearData.addAction(self.actionClearRoter)
        self.menuImage.addAction(self.actionCutoutImage)
        self.menuROV.addAction(self.actionCheckIp)
        self.menuROV.addAction(self.actionKeyControl)
        self.menuROV.addAction(self.actionRoterControl)
        self.menuBar.addAction(self.menuDete.menuAction())
        self.menuBar.addAction(self.menuROV.menuAction())
        self.menuBar.addAction(self.menuRoter.menuAction())
        self.menuBar.addAction(self.menuImage.menuAction())
        self.menuBar.addAction(self.menuClearData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuDete.setTitle(_translate("MainWindow", "检测方式"))
        self.menuRoter.setTitle(_translate("MainWindow", "遥控器"))
        self.menuClearData.setTitle(_translate("MainWindow", "清除数据"))
        self.menuImage.setTitle(_translate("MainWindow", "图像显示方式"))
        self.menuROV.setTitle(_translate("MainWindow", "水下机器人"))
        self.actionoDetBenShipin.setText(_translate("MainWindow", "检测本地视频"))
        self.actionClearRoter.setText(_translate("MainWindow", "清除遥控器数据"))
        self.actionCutoutImage.setText(_translate("MainWindow", "截取视频帧"))
        self.actionDetBenImage.setText(_translate("MainWindow", "检测本地图像"))
        self.actionScanRoter.setText(_translate("MainWindow", "扫描遥控器"))
        self.actionDetTimer.setText(_translate("MainWindow", "实时检测"))
        self.actionConnRoter.setText(_translate("MainWindow", "连接遥控器"))
        self.actionCheckIp.setText(_translate("MainWindow", "查看连接状态"))
        self.actionKeyControl.setText(_translate("MainWindow", "按键控制"))
        self.actionRoterControl.setText(_translate("MainWindow", "遥控器控制"))
        self.actionOpenRoter.setText(_translate("MainWindow", "打开遥控器"))
